### ISSUE TITLE
example code and possible upgrades

### ISSUE THREAD

**Issue by inf3rno** [DealerDotCom/jasmine-cucumber#2]
I think something like this would be much better in the readme file: 

tests/calculator.specs

	feature('Calculator: add')
        .scenario('should be able to add 2 numbers together')
            .when('I enter "1"')
            .and('I add "2"')
            .then('I should get "3"')
        .scenario('should be able to add 3 numbers together')
            .when('I enter "1"')
            .and('I add "2"')
            .and('I add "3"')
            .then('I should get "6"')
			
tests/calculator.steps
			
	featureSteps('Calculator:')
        .before(function(){
            this.values = [];
            this.total = null;
        })
        .when('I enter "(.*)"', function(value){
            this.values.push(Number(value));
        })
        .when('I add "(.*)"', function(value){
            this.values.push(Number(value));
        })
        .then('I should get "(.*)"', function(expectedTotal){
		    this.total = add.apply(null, this.values);
            expect(this.total).toBe(Number(expectedTotal));
        });

calculator.js
		
	function add(){
		var args = Array.prototype.slice.call(arguments);
		var total = 0;
		for (var i in args)
			total += args[i];
		return total;
	}

You put the implementation of the code you want to test into the steps file. It is better to decouple it by defining a function. Btw. this part is reusable:

```js
        .when('I enter "(.*)"', function(value){
            this.values.push(Number(value));
        })
        .when('I add "(.*)"', function(value){
            this.values.push(Number(value));
        })
```

Is it possible to reuse it somehow?

Another possible upgrade is auto-conversion of `\d` into numbers. Maybe it would be better to use a schema language like [mongoose schema](http://mongoosejs.com/docs/guide.html) instead of trying to parse the regex for that info, but I guess that would be overengineering.

**Comment by inf3rno** [comment]
cucumber.js has a transform keyword, which can do the auto-conversion. I think I'll create my own repo based on this and cucumber.

**Comment by jhoguet** [comment]
Thanks for the input, send me a link to the repo once you get it going, I would love to have a look
