### ISSUE TITLE
world support

### ISSUE THREAD

**Issue by inf3rno** [DealerDotCom/jasmine-cucumber#3]
I think there is a design problem with this project, because there is no world support. https://github.com/cucumber/cucumber-js#world

The feature files should be reusable in different world, for example if I have a feature file like this:

```js
feature("User")
    .scenario("change password")
        .given("I am a registered customer")
        .when("I change my old password to a new password")
        .then("I can login with the new password")
            .but("I cannot login with the old password any longer")
```

This change password scenario can be reused by different worlds:

 - by testing business logic
 - by testing database adapter
 - by e2e testing desktop html view
 - by e2e testing mobile html view
 - by e2e testing rest api

etc...

In the current implementation (afaik) this cannot be done, you can use a single feature definition only with a single step definition, which is a very bad constraint.

Btw. I think it would be wiser to use the gherkin AST: https://github.com/cucumber/gherkin3 , and write an own compiler for that. So you will be able to use gherkin, your custom js format, even rdf (json-ld) with a vocab, or anything else...

**Comment by jhoguet** [comment]
thanks for the feedback. 

Regarding world support, it isn't exactly baked in, but it is also quite simple, load the steps you want. 

So you may have a folder of specs, and then a folder per "world" of steps. And you always load the specs, but then load the steps for the world you're trying to test. 

To your point though, if the goal is to have a set of features you can use for all layers, then pure gherkin is a better choice. 

This library was born out of seeing that not work well in practice and having trouble integrating cucumberjs. 

Let me know what brought you here, and what you found best solved that problem. 

thanks again, 

jon

**Comment by inf3rno** [comment]
@jhoguet Thanks for the answer!

I am developing with TDD (with jasmine) and I have problems by refactoring the code, since the tests are not loosely coupled to the current implementation, and so by changing the implementation, I have to rewrite a lot of tests. Afaik BDD solves this problem so I felt the need to learn more about BDD and find tools I could use.

I don't like to create a new language for everything if it is not necessary, so I thought using js to describe features is a good choice. I checked gherkin with cucumberjs, and I think I might be wrong, and creating a new language was a good choice in this case either. Gherkin is good for describing high abstraction level concepts, while js is good for describing test implementation details (step definitions, fixtures, assertions, etc.). So I think now that both solutions are equally good.

I think your fluent interface can be easily implemented by cucumberjs as well, since they are using gherkin AST as an intermediate format. Probably their step definitions are not as simple as yours, I have had no time to check it properly yet, but it appeared more complicated at first glance.

What kind of problems did you have by integrating cucumberjs?

**Comment by jhoguet** [comment]
Main problem was that cucumberjs parses feature files. So in effect it wants to run first, which makes integrating with other testing frameworks more complex (eg karma, protractor, mocha, etc.)

The vision was that the abstraction of a non javascript feature file isn't buying you enough, there is a lot to be said for "its just javascript."

I haven't been able to carve enough time for this library, and it is now complex in its own way - so it fell short of the goal. 

I recently played with https://www.npmjs.com/package/mocha-cucumber which was easy to get off the ground but is missing the abstraction between the features and steps that both cucumberjs and jasmine-cucumber get you. 

Technically I could get jasmine-cucumber working with mocha quite easily, but it probably isn't worth it. 

Going to have to soak all this in and figure out where the right balance is.
